# Generated by Django 5.2.8 on 2026-06-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_gamestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestatus',
            name='nota',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamestatus',
            name='review',
            field=models.TextField(blank=True),
        ),
    ]
